a=int(input("enter number1"))
b=int(input("enter number2"))
print("The sum of two numbers is:" + str(a+b))
print("The diffefrence of two numbers is:" + str(a-b))
print("The product of two numbers is:" + str(a*b))